config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :edificios
  root :controller => 'edificios', :action => :home
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  belongs_to :edificio
end

app/models/edificio.rb
class Edificio < ApplicationRecord
    has_many :departamento
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
    @edificios = Edificio.all
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: "Departamento fue exitosamente creado" }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: "Departamento fue exitosamente actualizado" }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento fue exitosamente destruido" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:numero_de_departamento, :edificio_id)
    end
end

app/controllers/edificios_controller.rb
class EdificiosController < ApplicationController
  before_action :set_edificio, only: %i[ show edit update destroy ]
  
  def home
    redirect_to '/edificios'
  end

  # GET /edificios or /edificios.json
  def index
    @edificios = Edificio.all
  end

  # GET /edificios/1 or /edificios/1.json
  def show
  end

  # GET /edificios/new
  def new
    @edificio = Edificio.new
  end

  # GET /edificios/1/edit
  def edit
  end

  # POST /edificios or /edificios.json
  def create
    @edificio = Edificio.new(edificio_params)

    respond_to do |format|
      if @edificio.save
        format.html { redirect_to @edificio, notice: "Edificio fue creado exitosamente" }
        format.json { render :show, status: :created, location: @edificio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @edificio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edificios/1 or /edificios/1.json
  def update
    respond_to do |format|
      if @edificio.update(edificio_params)
        format.html { redirect_to @edificio, notice: "Edificio fue exitosamente actualizado." }
        format.json { render :show, status: :ok, location: @edificio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @edificio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edificios/1 or /edificios/1.json
  def destroy
    @edificio.destroy
    respond_to do |format|
      format.html { redirect_to edificios_url, notice: "Edificio fue exitosamente destruido." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edificio
      @edificio = Edificio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def edificio_params
      params.require(:edificio).permit(:nombre_de_edificio, :direccion, :ciudad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/edificios_helper.rb
module EdificiosHelper
end

app/views/departamentos/_form.html.erb
<div class='container'>
  <%= form_with(model: departamento) do |form| %>
    <% if departamento.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(departamento.errors.count, "error") %> No se puede guardar este departamento:</h2>

        <ul>
          <% departamento.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label for='numDepto'> <%= form.label :numero_de_departamento %></label>
      <%= form.text_field :numero_de_departamento, {id: 'numDpto', class: 'form-control'} %>
    </div>

    <div class="form-group">
      <label for='departamento_edificio_id'><%= form.label :edificio_id %></label>
      <!-- No sé cómo arreglar la línea 23 sorry :( -->
      <%= form.select :edificio_id, options_from_collection_for_select(p_edificios, :id, :nombre, p_departamento.edificio_id), {include_blank: "Seleccionar un hotel"}, class: 'form-select' %>
    
    </div>

    <div>
      <%= form.submit 'Crear departamento' , :class => 'btn btn-success' %>
    </div>
  <% end %>
  <br/>
  <%= link_to 'Atrás', departamentos_path %>
</div>

app/views/departamentos/edit.html.erb
<h1>Editando Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Mostrar', @departamento %> |
<%= link_to 'Atrás', departamentos_path %>

app/views/departamentos/index.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Departamentos</h1>
</div>


<div class="container">
  <table>
    <thead>
      <tr>
        <th>Número de departamento</th>
        <th>Edificio</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @departamentos.each do |departamento| %>
        <tr>
          <td><%= departamento.numero_de_departamento %></td>
          <td><%= departamento.edificio_id %></td>
          <td><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Mostrar', departamento %></button></td>
          <td><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Editar', edit_departamento_path(departamento) %></button></td>
          <td><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Eliminar', departamento, method: :delete, data: { confirm: '¿Está seguro?' } %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class='container'>
  <a 
    class="btn btn-success btn-lg btn-block" 
    style='color: #FFF !important'
    href="/departamentos/new">
    Crea un nuevo Departamento
  </a>
</div>

<%= render 'layouts/footer' %>

app/views/departamentos/new.html.erb
<%= render 'layouts/navbar' %>
<h1>Nuevo Departamento</h1>
<%= render 'form', departamento: @departamento, edificios: @edificios %>
<%= render 'layouts/footer' %>

app/views/departamentos/show.html.erb
<%= render 'layouts/navbar' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Número de departamento:</strong>
  <%= @departamento.numero_de_departamento %>
</p>

<p>
  <strong>Edificio:</strong>
  <%= @departamento.edificio_id %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/edificios/_form.html.erb
<div class = 'container'>
  <%= form_with(model: edificio) do |form| %>
    <% if edificio.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(edificio.errors.count, "error") %> prohibited this edificio from being saved:</h2>

        <ul>
          <% edificio.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label for='nombreEdificio'> <%= form.label :nombre_de_edificio %> </label>
      <%= form.text_field :nombre_de_edificio, {id: 'nombreEdificio', class: 'form-control'} %>
    </div>

    <div class="form-group">
      <label for='direccionEdificio'><%= form.label :direccion %></label>
      <%= form.text_field :direccion, {id: 'direccionEdificio', class: 'form-control'}  %>
    </div>

    <div class="form-group">
      <label for='ciudadEdificio'><%= form.label :ciudad %></label>
      <%= form.text_field :ciudad, {id: 'ciudadEdificio', class: 'form-control'}  %>
    </div>

    <div class="actions">
      <%= form.submit 'Crear Edificio', :class => 'btn btn-success'%>
    </div>
  <% end %>
  <br/>
  <%= link_to 'Back', edificios_path %>
</div>

app/views/edificios/edit.html.erb
<%= render 'layouts/navbar' %>

<h1>Editando Edificio</h1>

<%= render 'form', edificio: @edificio %>

<%= link_to 'Mostrar', @edificio %> |
<%= link_to 'Atrás', edificios_path %>

<%= render 'layouts/footer' %>

app/views/edificios/index.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Edificios</h1>
</div>

<div class="container">
  <table>
    <thead>
      <tr>
        <th>Nombre de Edificio</th>
        <th>Dirección</th>
        <th>Ciudad</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @edificios.each do |edificio| %>
        <tr>
          <td><%= edificio.nombre_de_edificio %></td>
          <td><%= edificio.direccion %></td>
          <td><%= edificio.ciudad %></td>
          <td><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Mostrar', edificio %></button></td>
          <td><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Editar', edit_edificio_path(edificio) %></button></td>
          <td><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Eliminar', edificio, method: :delete, data: { confirm: '¿Estás seguro?' } %></button></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="container">
  <a  
    class="btn btn-success btn-lg btn-block" 
    href="/edificios/new"
    style='color: #FFF !important'
    >
    Crea un nuevo Edificio
  </a>
</div>

<%= render 'layouts/footer' %>

app/views/edificios/new.html.erb
<%= render 'layouts/navbar' %>
<h1>Nuevo Edificio</h1>
<%= render 'form', edificio: @edificio %>

app/views/edificios/show.html.erb
<%= render 'layouts/navbar' %>
<div class='container'>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nombre de edificio:</strong>
    <%= @edificio.nombre_de_edificio %>
  </p>

  <p>
    <strong>Dirección:</strong>
    <%= @edificio.direccion %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= @edificio.ciudad %>
  </p>

  <%= link_to 'Editar', edit_edificio_path(@edificio) %> |
  <%= link_to 'Atrás', edificios_path %>
</div>
<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer class="text-center text-lg-start" style='margin-top: 100px'>
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom text-muted">
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
  </section>

  <section class="">
    <div class="container text-center text-md-start mt-5">

      <div class="row mt-3">

        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Da Silva Propiedades
          </h6>
          <p>
            Este software esta creado como prueba de término de curso de Emprendimiento Digital con Tecnologías Web.
          </p>
        </div>
  
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <h6 class="text-uppercase fw-bold mb-4">
            Edificios
          </h6>
          <p>
            <a href="#!" class="text-reset">Viña del Mar</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Valparaíso</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Reñaca</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Concón</a>
          </p>
        </div>
     
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
 
          <h6 class="text-uppercase fw-bold mb-4">
            Links Útiles
          </h6>
          <p>
            <a href="#!" class="text-reset">Quienes somos</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Misión</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Visión</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Ayuda</a>
          </p>
        </div>
        
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Contacto
          </h6>
          <p><i class="fas fa-home me-3"></i> Viña del Mar, Chile</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 56 32 222 222</p>
          <p><i class="fas fa-print me-3"></i> + 56 32 333 333</p>
        </div>
      </div>
    </div>
  </section>

  <div 
    class="text-center p-4 navbar-black" 
    style='background-color: #28a745; color: #FFF'
    >
    © 2021 Copyright
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand" href="/">Inicio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/edificios">Edificios<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/departamentos">Departamentos</a>
      </li>
    </ul>
    <span class="navbar-text">
      Da Silva Propiedades
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Examen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>